/* ═══════════════════════════════════════════════════════════════════
   TAMATO STUDIO — EXPORT
   Build the combined CSS-variables + build/AI style-prompt block, and
   hand off into /build or /ai with the prompt pre-pasted.
═══════════════════════════════════════════════════════════════════ */

export function buildExport(name, tokens) {
  const c = tokens.colors || {}, t = tokens.typography || {}, sp = tokens.spacing || {},
        b = tokens.borders || {}, sh = tokens.shadows || {}, a = tokens.animation || {};
  return `/* TAMATO DESIGN SYSTEM — ${name} */
/* Generated by Tamato Studio | tamato.design */
/* Copy this entire block into Tamato Build or Tamato AI */

/* === CSS VARIABLES === */
:root {
  --color-primary: ${c.primary || ''};
  --color-secondary: ${c.secondary || ''};
  --color-accent: ${c.accent || ''};
  --color-background: ${c.background || ''};
  --color-surface: ${c.surface || ''};
  --color-text: ${c.text || ''};
  --color-text-secondary: ${c.text_secondary || ''};
  --color-border: ${c.border || ''};
  --font-heading: '${t.heading_font || ''}', sans-serif;
  --font-body: '${t.body_font || ''}', sans-serif;
  --font-mono: '${t.mono_font || ''}', monospace;
  --font-size-base: ${t.base_size || ''};
  --font-scale: ${t.scale_ratio || ''};
  --space-xs: ${sp.xs || ''};
  --space-sm: ${sp.sm || ''};
  --space-md: ${sp.md || ''};
  --space-lg: ${sp.lg || ''};
  --space-xl: ${sp.xl || ''};
  --space-xxl: ${sp.xxl || ''};
  --radius-sm: ${b.radius_sm || ''};
  --radius-md: ${b.radius_md || ''};
  --radius-lg: ${b.radius_lg || ''};
  --shadow-sm: ${sh.sm || ''};
  --shadow-md: ${sh.md || ''};
  --shadow-lg: ${sh.lg || ''};
  --duration-fast: ${a.duration_fast || ''};
  --duration-base: ${a.duration_base || ''};
  --duration-slow: ${a.duration_slow || ''};
  --easing: ${a.easing || ''};
}

/* === TAMATO BUILD/AI STYLE PROMPT === */
/*
Apply this design system to the entire site:
Colors: primary ${c.primary}, secondary ${c.secondary}, accent ${c.accent}
Background: ${c.background}, Surface: ${c.surface}
Text: ${c.text} primary, ${c.text_secondary} secondary
Headings: ${t.heading_font} ${t.heading_weight}
Body: ${t.body_font} ${t.body_weight}, base size ${t.base_size}, scale ${t.scale_ratio}
Spacing base: ${sp.base} — use multiples throughout
Border radius: ${b.radius_md} standard, ${b.radius_lg} cards/modals
Shadows: ${sh.sm} subtle, ${sh.md} cards, ${sh.lg} modals
Animations: ${a.duration_fast} micro-interactions, ${a.duration_base} transitions, ${a.easing}
Overall aesthetic: ${tokens.aesthetic || ''}
Apply consistently to every element. This is the complete design identity.
*/`;
}

export function openInBuild(name, tokens) {
  sessionStorage.setItem('tm_prefill_prompt', promptOnly(name, tokens));
  window.open('/build/', '_blank');
}
export function openInAI(name, tokens) {
  sessionStorage.setItem('tm_ai_prefill', promptOnly(name, tokens));
  window.open('/ai/', '_blank');
}

function promptOnly(name, tokens) {
  const block = buildExport(name, tokens);
  const m = block.match(/=== TAMATO BUILD\/AI STYLE PROMPT ===\s*\/\*([\s\S]*?)\*\//);
  return `Use this design system:\n${m ? m[1].trim() : block}`;
}
